window.esdocSearchIndex = [
  [
    "@ignavia/util/src/cloner.js~cloner",
    "class/src/Cloner.js~Cloner.html",
    "<span>Cloner</span> <span class=\"search-result-import-path\">@ignavia/util/src/Cloner.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/color.js~color",
    "class/src/Color.js~Color.html",
    "<span>Color</span> <span class=\"search-result-import-path\">@ignavia/util/src/Color.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/event.js~event",
    "class/src/Event.js~Event.html",
    "<span>Event</span> <span class=\"search-result-import-path\">@ignavia/util/src/Event.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/eventmanager.js~eventmanager",
    "class/src/EventManager.js~EventManager.html",
    "<span>EventManager</span> <span class=\"search-result-import-path\">@ignavia/util/src/EventManager.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/gump/gumpmap.js~gumpmap",
    "class/src/gump/GumpMap.js~GumpMap.html",
    "<span>GumpMap</span> <span class=\"search-result-import-path\">@ignavia/util/src/gump/GumpMap.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/gump/gumppath.js~gumppath",
    "class/src/gump/GumpPath.js~GumpPath.html",
    "<span>GumpPath</span> <span class=\"search-result-import-path\">@ignavia/util/src/gump/GumpPath.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/gump/gumpset.js~gumpset",
    "class/src/gump/GumpSet.js~GumpSet.html",
    "<span>GumpSet</span> <span class=\"search-result-import-path\">@ignavia/util/src/gump/GumpSet.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/idgenerator.js~idgenerator",
    "class/src/IDGenerator.js~IDGenerator.html",
    "<span>IDGenerator</span> <span class=\"search-result-import-path\">@ignavia/util/src/IDGenerator.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/plugin.js~plugin",
    "class/src/Plugin.js~Plugin.html",
    "<span>Plugin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Plugin.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tolkien/tolkien1to1map.js~tolkien1to1map",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html",
    "<span>Tolkien1To1Map</span> <span class=\"search-result-import-path\">@ignavia/util/src/tolkien/Tolkien1To1Map.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tolkien/tolkien1tonmap.js~tolkien1tonmap",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html",
    "<span>Tolkien1ToNMap</span> <span class=\"search-result-import-path\">@ignavia/util/src/tolkien/Tolkien1ToNMap.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tolkien/tolkienmtonmap.js~tolkienmtonmap",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html",
    "<span>TolkienMToNMap</span> <span class=\"search-result-import-path\">@ignavia/util/src/tolkien/TolkienMToNMap.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tolkien/tolkienmap.js~tolkienmap",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html",
    "<span>TolkienMap</span> <span class=\"search-result-import-path\">@ignavia/util/src/tolkien/TolkienMap.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tortilla/tortillageneratorfunction.js~tortillageneratorfunction",
    "class/src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction.html",
    "<span>TortillaGeneratorFunction</span> <span class=\"search-result-import-path\">@ignavia/util/src/tortilla/TortillaGeneratorFunction.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tortilla/tortillaiterable.js~tortillaiterable",
    "class/src/tortilla/TortillaIterable.js~TortillaIterable.html",
    "<span>TortillaIterable</span> <span class=\"search-result-import-path\">@ignavia/util/src/tortilla/TortillaIterable.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tortilla/tortillaiterator.js~tortillaiterator",
    "class/src/tortilla/TortillaIterator.js~TortillaIterator.html",
    "<span>TortillaIterator</span> <span class=\"search-result-import-path\">@ignavia/util/src/tortilla/TortillaIterator.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/tortilla/tortillawrapper.js~tortillawrapper",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html",
    "<span>TortillaWrapper</span> <span class=\"search-result-import-path\">@ignavia/util/src/tortilla/TortillaWrapper.js</span>",
    "class"
  ],
  [
    "@ignavia/util/src/cloneable.js~cloneableextendedmixin",
    "variable/index.html#static-variable-cloneableExtendedMixin",
    "<span>cloneableExtendedMixin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Cloneable.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/cloneable.js~cloneablemixin",
    "variable/index.html#static-variable-cloneableMixin",
    "<span>cloneableMixin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Cloneable.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/cloneable.js~cloneablesymbols",
    "variable/index.html#static-variable-cloneableSymbols",
    "<span>cloneableSymbols</span> <span class=\"search-result-import-path\">@ignavia/util/src/Cloneable.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/tolkien/tolkien.js~compose",
    "function/index.html#static-function-compose",
    "<span>compose</span> <span class=\"search-result-import-path\">@ignavia/util/src/tolkien/tolkien.js</span>",
    "function"
  ],
  [
    "@ignavia/util/src/extensible.js~extensibleextendedmixin",
    "variable/index.html#static-variable-extensibleExtendedMixin",
    "<span>extensibleExtendedMixin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Extensible.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/extensible.js~extensiblemixin",
    "variable/index.html#static-variable-extensibleMixin",
    "<span>extensibleMixin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Extensible.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/extensible.js~extensiblesymbols",
    "variable/index.html#static-variable-extensibleSymbols",
    "<span>extensibleSymbols</span> <span class=\"search-result-import-path\">@ignavia/util/src/Extensible.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/observable.js~observableextendedmixin",
    "variable/index.html#static-variable-observableExtendedMixin",
    "<span>observableExtendedMixin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Observable.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/observable.js~observablemixin",
    "variable/index.html#static-variable-observableMixin",
    "<span>observableMixin</span> <span class=\"search-result-import-path\">@ignavia/util/src/Observable.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/observable.js~observablesymbols",
    "variable/index.html#static-variable-observableSymbols",
    "<span>observableSymbols</span> <span class=\"search-result-import-path\">@ignavia/util/src/Observable.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/color.js~predefinedcolors",
    "variable/index.html#static-variable-predefinedColors",
    "<span>predefinedColors</span> <span class=\"search-result-import-path\">@ignavia/util/src/Color.js</span>",
    "variable"
  ],
  [
    "@ignavia/util/src/tortilla/tortilla.js~tortilla",
    "function/index.html#static-function-tortilla",
    "<span>tortilla</span> <span class=\"search-result-import-path\">@ignavia/util/src/tortilla/tortilla.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/cloneable.js",
    "file/src/Cloneable.js.html",
    "src/Cloneable.js",
    "file"
  ],
  [
    "src/cloner.js",
    "file/src/Cloner.js.html",
    "src/Cloner.js",
    "file"
  ],
  [
    "src/cloner.js~cloner#clone",
    "class/src/Cloner.js~Cloner.html#instance-method-clone",
    "src/Cloner.js~Cloner#clone",
    "method"
  ],
  [
    "src/cloner.js~cloner#constructor",
    "class/src/Cloner.js~Cloner.html#instance-constructor-constructor",
    "src/Cloner.js~Cloner#constructor",
    "method"
  ],
  [
    "src/color.js",
    "file/src/Color.js.html",
    "src/Color.js",
    "file"
  ],
  [
    "src/color.js~color#alpha",
    "class/src/Color.js~Color.html#instance-member-alpha",
    "src/Color.js~Color#alpha",
    "member"
  ],
  [
    "src/color.js~color#constructor",
    "class/src/Color.js~Color.html#instance-constructor-constructor",
    "src/Color.js~Color#constructor",
    "method"
  ],
  [
    "src/color.js~color#hex",
    "class/src/Color.js~Color.html#instance-member-hex",
    "src/Color.js~Color#hex",
    "member"
  ],
  [
    "src/color.js~color#tohsla",
    "class/src/Color.js~Color.html#instance-method-toHSLA",
    "src/Color.js~Color#toHSLA",
    "method"
  ],
  [
    "src/color.js~color#torgba",
    "class/src/Color.js~Color.html#instance-method-toRGBA",
    "src/Color.js~Color#toRGBA",
    "method"
  ],
  [
    "src/color.js~color#tostring",
    "class/src/Color.js~Color.html#instance-method-toString",
    "src/Color.js~Color#toString",
    "method"
  ],
  [
    "src/color.js~color.fromhsla",
    "class/src/Color.js~Color.html#static-method-fromHSLA",
    "src/Color.js~Color.fromHSLA",
    "method"
  ],
  [
    "src/color.js~color.fromrgba",
    "class/src/Color.js~Color.html#static-method-fromRGBA",
    "src/Color.js~Color.fromRGBA",
    "method"
  ],
  [
    "src/event.js",
    "file/src/Event.js.html",
    "src/Event.js",
    "file"
  ],
  [
    "src/event.js~event#constructor",
    "class/src/Event.js~Event.html#instance-constructor-constructor",
    "src/Event.js~Event#constructor",
    "method"
  ],
  [
    "src/event.js~event#data",
    "class/src/Event.js~Event.html#instance-member-data",
    "src/Event.js~Event#data",
    "member"
  ],
  [
    "src/event.js~event#source",
    "class/src/Event.js~Event.html#instance-member-source",
    "src/Event.js~Event#source",
    "member"
  ],
  [
    "src/event.js~event#type",
    "class/src/Event.js~Event.html#instance-member-type",
    "src/Event.js~Event#type",
    "member"
  ],
  [
    "src/eventmanager.js",
    "file/src/EventManager.js.html",
    "src/EventManager.js",
    "file"
  ],
  [
    "src/eventmanager.js~eventmanager#[observablesymbols.addlistener]",
    "class/src/EventManager.js~EventManager.html#instance-method-[observableSymbols.addListener]",
    "src/EventManager.js~EventManager#[observableSymbols.addListener]",
    "method"
  ],
  [
    "src/eventmanager.js~eventmanager#[observablesymbols.fireevent]",
    "class/src/EventManager.js~EventManager.html#instance-method-[observableSymbols.fireEvent]",
    "src/EventManager.js~EventManager#[observableSymbols.fireEvent]",
    "method"
  ],
  [
    "src/eventmanager.js~eventmanager#[observablesymbols.removelistener]",
    "class/src/EventManager.js~EventManager.html#instance-method-[observableSymbols.removeListener]",
    "src/EventManager.js~EventManager#[observableSymbols.removeListener]",
    "method"
  ],
  [
    "src/eventmanager.js~eventmanager#constructor",
    "class/src/EventManager.js~EventManager.html#instance-constructor-constructor",
    "src/EventManager.js~EventManager#constructor",
    "method"
  ],
  [
    "src/eventmanager.js~eventmanager#listenertotypes",
    "class/src/EventManager.js~EventManager.html#instance-member-listenerToTypes",
    "src/EventManager.js~EventManager#listenerToTypes",
    "member"
  ],
  [
    "src/eventmanager.js~eventmanager#typetolisteners",
    "class/src/EventManager.js~EventManager.html#instance-member-typeToListeners",
    "src/EventManager.js~EventManager#typeToListeners",
    "member"
  ],
  [
    "src/eventmanager.js~eventmanager.makeevent",
    "class/src/EventManager.js~EventManager.html#static-method-makeEvent",
    "src/EventManager.js~EventManager.makeEvent",
    "method"
  ],
  [
    "src/extensible.js",
    "file/src/Extensible.js.html",
    "src/Extensible.js",
    "file"
  ],
  [
    "src/idgenerator.js",
    "file/src/IDGenerator.js.html",
    "src/IDGenerator.js",
    "file"
  ],
  [
    "src/idgenerator.js~idgenerator#avoid",
    "class/src/IDGenerator.js~IDGenerator.html#instance-method-avoid",
    "src/IDGenerator.js~IDGenerator#avoid",
    "method"
  ],
  [
    "src/idgenerator.js~idgenerator#constructor",
    "class/src/IDGenerator.js~IDGenerator.html#instance-constructor-constructor",
    "src/IDGenerator.js~IDGenerator#constructor",
    "method"
  ],
  [
    "src/idgenerator.js~idgenerator#increasetoatleast",
    "class/src/IDGenerator.js~IDGenerator.html#instance-method-increaseToAtLeast",
    "src/IDGenerator.js~IDGenerator#increaseToAtLeast",
    "method"
  ],
  [
    "src/idgenerator.js~idgenerator#next",
    "class/src/IDGenerator.js~IDGenerator.html#instance-method-next",
    "src/IDGenerator.js~IDGenerator#next",
    "method"
  ],
  [
    "src/idgenerator.js~idgenerator#prefix",
    "class/src/IDGenerator.js~IDGenerator.html#instance-member-prefix",
    "src/IDGenerator.js~IDGenerator#prefix",
    "member"
  ],
  [
    "src/observable.js",
    "file/src/Observable.js.html",
    "src/Observable.js",
    "file"
  ],
  [
    "src/plugin.js",
    "file/src/Plugin.js.html",
    "src/Plugin.js",
    "file"
  ],
  [
    "src/plugin.js~plugin#[cloneablesymbols.clone]",
    "class/src/Plugin.js~Plugin.html#instance-method-[cloneableSymbols.clone]",
    "src/Plugin.js~Plugin#[cloneableSymbols.clone]",
    "method"
  ],
  [
    "src/plugin.js~plugin#constructor",
    "class/src/Plugin.js~Plugin.html#instance-constructor-constructor",
    "src/Plugin.js~Plugin#constructor",
    "method"
  ],
  [
    "src/plugin.js~plugin#register",
    "class/src/Plugin.js~Plugin.html#instance-method-register",
    "src/Plugin.js~Plugin#register",
    "method"
  ],
  [
    "src/plugin.js~plugin#unregister",
    "class/src/Plugin.js~Plugin.html#instance-method-unregister",
    "src/Plugin.js~Plugin#unregister",
    "method"
  ],
  [
    "src/gump/gumpmap.js",
    "file/src/gump/GumpMap.js.html",
    "src/gump/GumpMap.js",
    "file"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#[symbol.iterator]",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-[Symbol.iterator]",
    "src/gump/GumpMap.js~GumpMap#[Symbol.iterator]",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#add",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-add",
    "src/gump/GumpMap.js~GumpMap#add",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#clear",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-clear",
    "src/gump/GumpMap.js~GumpMap#clear",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#constructor",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-constructor-constructor",
    "src/gump/GumpMap.js~GumpMap#constructor",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#delete",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-delete",
    "src/gump/GumpMap.js~GumpMap#delete",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#entries",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-entries",
    "src/gump/GumpMap.js~GumpMap#entries",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#get",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-get",
    "src/gump/GumpMap.js~GumpMap#get",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#has",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-has",
    "src/gump/GumpMap.js~GumpMap#has",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#keys",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-keys",
    "src/gump/GumpMap.js~GumpMap#keys",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#paths",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-paths",
    "src/gump/GumpMap.js~GumpMap#paths",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#purgeemptycontainers",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-purgeEmptyContainers",
    "src/gump/GumpMap.js~GumpMap#purgeEmptyContainers",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#set",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-set",
    "src/gump/GumpMap.js~GumpMap#set",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#size",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-member-size",
    "src/gump/GumpMap.js~GumpMap#size",
    "member"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#updatewithfunction",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-updateWithFunction",
    "src/gump/GumpMap.js~GumpMap#updateWithFunction",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#updatewithliteral",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-updateWithLiteral",
    "src/gump/GumpMap.js~GumpMap#updateWithLiteral",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap#values",
    "class/src/gump/GumpMap.js~GumpMap.html#instance-method-values",
    "src/gump/GumpMap.js~GumpMap#values",
    "method"
  ],
  [
    "src/gump/gumpmap.js~gumpmap.fromobject",
    "class/src/gump/GumpMap.js~GumpMap.html#static-method-fromObject",
    "src/gump/GumpMap.js~GumpMap.fromObject",
    "method"
  ],
  [
    "src/gump/gumppath.js",
    "file/src/gump/GumpPath.js.html",
    "src/gump/GumpPath.js",
    "file"
  ],
  [
    "src/gump/gumppath.js~gumppath#append",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-append",
    "src/gump/GumpPath.js~GumpPath#append",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#constructor",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-constructor-constructor",
    "src/gump/GumpPath.js~GumpPath#constructor",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#head",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-head",
    "src/gump/GumpPath.js~GumpPath#head",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#init",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-init",
    "src/gump/GumpPath.js~GumpPath#init",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#insertat",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-insertAt",
    "src/gump/GumpPath.js~GumpPath#insertAt",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#isempty",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-isEmpty",
    "src/gump/GumpPath.js~GumpPath#isEmpty",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#keyat",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-keyAt",
    "src/gump/GumpPath.js~GumpPath#keyAt",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#last",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-last",
    "src/gump/GumpPath.js~GumpPath#last",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#length",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-get-length",
    "src/gump/GumpPath.js~GumpPath#length",
    "member"
  ],
  [
    "src/gump/gumppath.js~gumppath#prepend",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-prepend",
    "src/gump/GumpPath.js~GumpPath#prepend",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#tail",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-tail",
    "src/gump/GumpPath.js~GumpPath#tail",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath#tostring",
    "class/src/gump/GumpPath.js~GumpPath.html#instance-method-toString",
    "src/gump/GumpPath.js~GumpPath#toString",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath.fromstring",
    "class/src/gump/GumpPath.js~GumpPath.html#static-method-fromString",
    "src/gump/GumpPath.js~GumpPath.fromString",
    "method"
  ],
  [
    "src/gump/gumppath.js~gumppath.togumppath",
    "class/src/gump/GumpPath.js~GumpPath.html#static-method-toGumpPath",
    "src/gump/GumpPath.js~GumpPath.toGumpPath",
    "method"
  ],
  [
    "src/gump/gumpset.js",
    "file/src/gump/GumpSet.js.html",
    "src/gump/GumpSet.js",
    "file"
  ],
  [
    "src/gump/gumpset.js~gumpset#[symbol.iterator]",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-[Symbol.iterator]",
    "src/gump/GumpSet.js~GumpSet#[Symbol.iterator]",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#add",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-add",
    "src/gump/GumpSet.js~GumpSet#add",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#clear",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-clear",
    "src/gump/GumpSet.js~GumpSet#clear",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#constructor",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-constructor-constructor",
    "src/gump/GumpSet.js~GumpSet#constructor",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#delete",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-delete",
    "src/gump/GumpSet.js~GumpSet#delete",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#entries",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-entries",
    "src/gump/GumpSet.js~GumpSet#entries",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#has",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-has",
    "src/gump/GumpSet.js~GumpSet#has",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#keys",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-keys",
    "src/gump/GumpSet.js~GumpSet#keys",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#size",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-get-size",
    "src/gump/GumpSet.js~GumpSet#size",
    "member"
  ],
  [
    "src/gump/gumpset.js~gumpset#tostring",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-toString",
    "src/gump/GumpSet.js~GumpSet#toString",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#updatewithfunction",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-updateWithFunction",
    "src/gump/GumpSet.js~GumpSet#updateWithFunction",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#updatewithliteral",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-updateWithLiteral",
    "src/gump/GumpSet.js~GumpSet#updateWithLiteral",
    "method"
  ],
  [
    "src/gump/gumpset.js~gumpset#values",
    "class/src/gump/GumpSet.js~GumpSet.html#instance-method-values",
    "src/gump/GumpSet.js~GumpSet#values",
    "method"
  ],
  [
    "src/gump/gump.js",
    "file/src/gump/gump.js.html",
    "src/gump/gump.js",
    "file"
  ],
  [
    "src/tolkien/tolkien1to1map.js",
    "file/src/tolkien/Tolkien1To1Map.js.html",
    "src/tolkien/Tolkien1To1Map.js",
    "file"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#constructor",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-constructor-constructor",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#constructor",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#convertxtoy",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-convertXToY",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#convertXToY",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#convertytox",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-convertYToX",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#convertYToX",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#deletepair",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-deletePair",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#deletePair",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#deletex",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-deleteX",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#deleteX",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#deletey",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-deleteY",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#deleteY",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#entries",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-entries",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#entries",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#haspair",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-hasPair",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#hasPair",
    "method"
  ],
  [
    "src/tolkien/tolkien1to1map.js~tolkien1to1map#xs",
    "class/src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map.html#instance-method-xs",
    "src/tolkien/Tolkien1To1Map.js~Tolkien1To1Map#xs",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js",
    "file/src/tolkien/Tolkien1ToNMap.js.html",
    "src/tolkien/Tolkien1ToNMap.js",
    "file"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#constructor",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-constructor-constructor",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#constructor",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#convertxtoy",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-convertXToY",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#convertXToY",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#convertytox",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-convertYToX",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#convertYToX",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#deletepair",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-deletePair",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#deletePair",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#deletex",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-deleteX",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#deleteX",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#deletey",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-deleteY",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#deleteY",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#entries",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-entries",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#entries",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#haspair",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-hasPair",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#hasPair",
    "method"
  ],
  [
    "src/tolkien/tolkien1tonmap.js~tolkien1tonmap#xs",
    "class/src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap.html#instance-method-xs",
    "src/tolkien/Tolkien1ToNMap.js~Tolkien1ToNMap#xs",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js",
    "file/src/tolkien/TolkienMToNMap.js.html",
    "src/tolkien/TolkienMToNMap.js",
    "file"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#constructor",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-constructor-constructor",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#constructor",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#convertxtoy",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-convertXToY",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#convertXToY",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#convertytox",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-convertYToX",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#convertYToX",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#deletepair",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-deletePair",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#deletePair",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#deletex",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-deleteX",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#deleteX",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#deletey",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-deleteY",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#deleteY",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#entries",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-entries",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#entries",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#haspair",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-hasPair",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#hasPair",
    "method"
  ],
  [
    "src/tolkien/tolkienmtonmap.js~tolkienmtonmap#xs",
    "class/src/tolkien/TolkienMToNMap.js~TolkienMToNMap.html#instance-method-xs",
    "src/tolkien/TolkienMToNMap.js~TolkienMToNMap#xs",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js",
    "file/src/tolkien/TolkienMap.js.html",
    "src/tolkien/TolkienMap.js",
    "file"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#[symbol.iterator]",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-[Symbol.iterator]",
    "src/tolkien/TolkienMap.js~TolkienMap#[Symbol.iterator]",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#add",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-add",
    "src/tolkien/TolkienMap.js~TolkienMap#add",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#clear",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-clear",
    "src/tolkien/TolkienMap.js~TolkienMap#clear",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#constructor",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-constructor-constructor",
    "src/tolkien/TolkienMap.js~TolkienMap#constructor",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#convertxtoy",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-convertXToY",
    "src/tolkien/TolkienMap.js~TolkienMap#convertXToY",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#convertytox",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-convertYToX",
    "src/tolkien/TolkienMap.js~TolkienMap#convertYToX",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#delete",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-delete",
    "src/tolkien/TolkienMap.js~TolkienMap#delete",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#deletepair",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-deletePair",
    "src/tolkien/TolkienMap.js~TolkienMap#deletePair",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#deletex",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-deleteX",
    "src/tolkien/TolkienMap.js~TolkienMap#deleteX",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#deletey",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-deleteY",
    "src/tolkien/TolkienMap.js~TolkienMap#deleteY",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#entries",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-entries",
    "src/tolkien/TolkienMap.js~TolkienMap#entries",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#has",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-has",
    "src/tolkien/TolkienMap.js~TolkienMap#has",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#haseither",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-hasEither",
    "src/tolkien/TolkienMap.js~TolkienMap#hasEither",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#haspair",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-hasPair",
    "src/tolkien/TolkienMap.js~TolkienMap#hasPair",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#hasx",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-hasX",
    "src/tolkien/TolkienMap.js~TolkienMap#hasX",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#hasy",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-hasY",
    "src/tolkien/TolkienMap.js~TolkienMap#hasY",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#set",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-set",
    "src/tolkien/TolkienMap.js~TolkienMap#set",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#size",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-get-size",
    "src/tolkien/TolkienMap.js~TolkienMap#size",
    "member"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#xs",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-xs",
    "src/tolkien/TolkienMap.js~TolkienMap#xs",
    "method"
  ],
  [
    "src/tolkien/tolkienmap.js~tolkienmap#ys",
    "class/src/tolkien/TolkienMap.js~TolkienMap.html#instance-method-ys",
    "src/tolkien/TolkienMap.js~TolkienMap#ys",
    "method"
  ],
  [
    "src/tolkien/tolkien.js",
    "file/src/tolkien/tolkien.js.html",
    "src/tolkien/tolkien.js",
    "file"
  ],
  [
    "src/tortilla/tortillageneratorfunction.js",
    "file/src/tortilla/TortillaGeneratorFunction.js.html",
    "src/tortilla/TortillaGeneratorFunction.js",
    "file"
  ],
  [
    "src/tortilla/tortillageneratorfunction.js~tortillageneratorfunction#[symbol.iterator]",
    "class/src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction.html#instance-method-[Symbol.iterator]",
    "src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction#[Symbol.iterator]",
    "method"
  ],
  [
    "src/tortilla/tortillageneratorfunction.js~tortillageneratorfunction#apply",
    "class/src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction.html#instance-method-apply",
    "src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction#apply",
    "method"
  ],
  [
    "src/tortilla/tortillageneratorfunction.js~tortillageneratorfunction#constructor",
    "class/src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction.html#instance-constructor-constructor",
    "src/tortilla/TortillaGeneratorFunction.js~TortillaGeneratorFunction#constructor",
    "method"
  ],
  [
    "src/tortilla/tortillaiterable.js",
    "file/src/tortilla/TortillaIterable.js.html",
    "src/tortilla/TortillaIterable.js",
    "file"
  ],
  [
    "src/tortilla/tortillaiterable.js~tortillaiterable#[symbol.iterator]",
    "class/src/tortilla/TortillaIterable.js~TortillaIterable.html#instance-method-[Symbol.iterator]",
    "src/tortilla/TortillaIterable.js~TortillaIterable#[Symbol.iterator]",
    "method"
  ],
  [
    "src/tortilla/tortillaiterable.js~tortillaiterable#constructor",
    "class/src/tortilla/TortillaIterable.js~TortillaIterable.html#instance-constructor-constructor",
    "src/tortilla/TortillaIterable.js~TortillaIterable#constructor",
    "method"
  ],
  [
    "src/tortilla/tortillaiterator.js",
    "file/src/tortilla/TortillaIterator.js.html",
    "src/tortilla/TortillaIterator.js",
    "file"
  ],
  [
    "src/tortilla/tortillaiterator.js~tortillaiterator#[symbol.iterator]",
    "class/src/tortilla/TortillaIterator.js~TortillaIterator.html#instance-method-[Symbol.iterator]",
    "src/tortilla/TortillaIterator.js~TortillaIterator#[Symbol.iterator]",
    "method"
  ],
  [
    "src/tortilla/tortillaiterator.js~tortillaiterator#constructor",
    "class/src/tortilla/TortillaIterator.js~TortillaIterator.html#instance-constructor-constructor",
    "src/tortilla/TortillaIterator.js~TortillaIterator#constructor",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js",
    "file/src/tortilla/TortillaWrapper.js.html",
    "src/tortilla/TortillaWrapper.js",
    "file"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#[symbol.iterator]",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-[Symbol.iterator]",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#[Symbol.iterator]",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#chunk",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-chunk",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#chunk",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#compact",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-compact",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#compact",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#constructor",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-constructor-constructor",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#constructor",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#drop",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-drop",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#drop",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#dropwhile",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-dropWhile",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#dropWhile",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#filter",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-filter",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#filter",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#flatten",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-flatten",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#flatten",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#head",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-head",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#head",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#isempty",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-isEmpty",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#isEmpty",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#map",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-map",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#map",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#reject",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-reject",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#reject",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#slice",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-slice",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#slice",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#tail",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-tail",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#tail",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#take",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-take",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#take",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#takewhile",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-takeWhile",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#takeWhile",
    "method"
  ],
  [
    "src/tortilla/tortillawrapper.js~tortillawrapper#without",
    "class/src/tortilla/TortillaWrapper.js~TortillaWrapper.html#instance-method-without",
    "src/tortilla/TortillaWrapper.js~TortillaWrapper#without",
    "method"
  ],
  [
    "src/tortilla/tortilla.js",
    "file/src/tortilla/tortilla.js.html",
    "src/tortilla/tortilla.js",
    "file"
  ],
  [
    "src/util.js",
    "file/src/util.js.html",
    "src/util.js",
    "file"
  ]
]